SELECT
    tlr.id AS listing_id,
    tlr.scrape_id AS scrape_id,
    CAST(tlr.last_scraped AS DATE) AS last_scraped,
    tlr.name AS "name",
    tlr.host_id AS host_id,
    tlr.host_name AS host_name,
    CAST(tlr.host_since AS DATE) AS host_since,
    tlr.host_location AS host_location,
    tlr.host_response_time AS host_response_time,
    tlr.host_response_rate AS host_response_rate,
    tlr.host_acceptance_rate AS host_acceptance_rate,
    tlr.host_is_superhost AS host_is_superhost,
    tlr.host_total_listings_count AS host_total_listings_count,
    tlr.host_has_profile_pic AS host_has_profile_pic,
    tlr.host_identity_verified AS host_identity_verified,
    tlr.property_type AS property_type,
    tlr.room_type AS room_type,
    tlr.accommodates AS accommodates,
    tlr.bathrooms_text AS bathrooms_text,
    tlr.bedrooms AS bedrooms,
    tlr.beds AS beds,
    tlr.amenities AS amenities,
    tlr.price AS price,
    tlr.minimum_nights AS minimum_nights,
    tlr.maximum_nights AS maximum_nights,
    tlr.has_availability AS has_availability,
    tlr.instant_bookable AS instant_bookable,
    CAST(tlr.calendar_last_scraped AS DATE) AS calendar_last_scraped,
    tlr.number_of_reviews AS number_of_reviews,
    CAST(tlr.first_review AS DATE) AS first_review,
    CAST(tlr.last_review AS DATE) AS last_review,
    tlr.review_scores_rating AS review_scores_rating,
    tlr.review_scores_accuracy AS review_scores_accuracy,
    tlr.review_scores_cleanliness AS review_scores_cleanliness,
    tlr.review_scores_checkin AS review_scores_checkin,
    tlr.review_scores_communication AS review_scores_communication,
    tlr.review_scores_location AS review_scores_location,
    tlr.review_scores_value AS review_scores_value,
    tlr.reviews_per_month AS reviews_per_month
FROM public.tb_listings_raw as tlr
WHERE COALESCE (
      tlr.first_review,
      tlr.last_review
      ) IS NOT NULL
